#160 Prevent rerender of background Image on tab change
netguru/sticky-parallax-header pull request #171
Opened 2020-10-24 14:21 UTC by brooksbecton

fixes: #160 

**Note**: Could I get the `hacktoberfest-accepted` label on this PR if everything looks ok? 

I edited the example to show that the background image will still re render if the source uri changes by showing a different background image on refresh
![Large GIF (378x758)](https://user-images.githubusercontent.com/9373516/97084027-17249e00-15e2-11eb-8391-02dae3cf91bf.gif)

2020-12-09 07:51 UTC, maciejBudzinskiNG requested changes

2020-12-09 07:51 UTC, maciejBudzinskiNG commented on src/StickyParallaxHeader.js
> +const HeaderBackgroundImage = (props) => {
The component looks good, but I would like you to move it (including styles) to a separate file under the src/components/HeaderBackgroundImage directory.

2020-12-09 07:51 UTC, maciejBudzinskiNG commented on src/StickyParallaxHeader.js
> +  prevProps.backgroundImage.uri === props.backgroundImage.uri;
Don't we need to add conditions for other props as well?
If `backgroundHeight` or `background` prop changes, the component still needs to rerender.

2020-12-09 07:52 UTC, maciejBudzinskiNG requested changes
Thank you for your work on this issue. Check my comments 🙂

2020-12-11 13:16 UTC, brooksbecton commented
I've made these changes.

2021-03-29 14:43 UTC, Ciberusps commented
🙃

2021-05-17 16:38 UTC, IdaszakDaniel approved these changes

2021-05-17 16:39 UTC, merged